#!/bin/bash

./clean

rm -f ALL_Tests.log

here=`pwd`

#for ExternalF90 in gfortran ifort pgf90 nagfor
for F90 in gfortran
do
for OPT in 0 1
do
for OMP in 0 1
do
for LAPACK in 0 1
do
for INT in 4 8
do
  echo xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                >> ALL_Tests.log
  echo xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                >> ALL_Tests.log
  echo $F90 OPT=$OPT OMP=$OMP LAPACK=$LAPACK "INT="$INT >> ALL_Tests.log
  echo xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                >> ALL_Tests.log
  echo xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                >> ALL_Tests.log
  cd ..
    RES="res_dnSV_dnPoly_"$F90"_Opt"$OPT"_OMP"$OMP"_Lapack"$LAPACK"_INT"$INT
    XLOG="comp_"$F90"_Opt"$OPT"_OMP"$OMP"_Lapack"$LAPACK"_INT"$INT".log"
    make F90=$F90 OPT=$OPT OMP=$OMP LAPACK=$LAPACK INT=$INT lib > $here/$XLOG 2>&1
    make F90=$F90 OPT=$OPT OMP=$OMP LAPACK=$LAPACK INT=$INT ut > $here/$RES 2> $here/$XLOG
  cd  $here
  grep "Number of error" $RES  >> ALL_Tests.log

done
done
done
done
done

