#!/bin/bash


CleanType=$1
CleanDIR=$2
CleanList=$3

echo "The script command is: \"$0 $@\""
echo CleanType: $CleanType
echo CleanDIR:  $CleanDIR
echo CleanList: $CleanList

if test -z "$CleanType"
then
  echo "The present script, cleanExtLib, has three arguments:"
  echo "    The first argument, the cleaning type: cleanall or cleanlocextlib"
  echo "    The second argument, the directory to be cleaned"
  echo "    The third argument, the list of module(s) to be cleaned"
  exit 1
fi

if test -z "$CleanList"
then
  echo No module to be cleaned!
  exit 0
fi

if test -z "$CleanDIR"
then
  echo No or empty second argument!
  exit 0
fi

if test ! -d $CleanDIR
then
  echo The directory $CleanDIR does not exist!
  exit 0
fi

if [ "$CleanType" = "cleanall" ]
then
  cd $CleanDIR
  for dirlib in $CleanList
  do
    echo $dirlib

    #remove the link
    rm -fr $dirlib

    #clean the libraries
    test -d $dirlib"_loc" &&  make -C $dirlib"_loc" --silent cleanall &> /dev/null
    #test -d $dirlib"_loc" && make -C $dirlib"_loc" cleanall
  done
elif [ "$CleanType" = "cleanlocextlib" ]
then
  cd $CleanDIR
  for dirlib in $CleanList
  do
    echo $dirlib
 
    #remove the link
    rm -fr $dirlib

    #remove the directory
    rm -rf $dirlib"_loc"
  done
else
  echo "The present script, cleanExtLib, has three arguments:"
  echo "    The first argument, the cleaning type: cleanall or cleanlocextlib"
  echo "    The second argument, the directory to be cleaned"
  echo "    The third argument, the list of module(s) to be cleaned"
  exit 1
fi
